rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2.1.1
matrix:
  allow_failures:
    - rvm: 2.1.0
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
before_install:
  - gem update --system 2.1.11
  - gem --version